[tool.poetry]
name = "ssgweb"
version = "0.1.0"
description = "Static Site Generator files for the ErlenePsyD.com website"
authors = ["Neil Johnson <neil@cadent.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pelican = "^4.7.2"
Markdown = "^3.3.6"
typogrify = "^2.0.7"
pelican-image-process = "^2.1.3"
pelican-photos = "^1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
